version: "3.9"

services:
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./hotel-booking-api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./hotel-booking-api/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ./hotel-booking
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
